# here we are talking about Exception & assertion

items = 1

'''
if items !=2 :
    raise Exception("The numbers are not matching")
else:
    print("The numbers are fine")

'''

assert(items == 5)